const lessonSamples = {
  'lesson-greetings': {
    _id: 'lesson-greetings',
    title: 'Greetings',
    textContent:
      'Hello! This lesson helps you greet someone politely.\n\nSay "Hello" or "Hi" with a smile.\n\nAsk "How are you?" and respond with "I am good, thank you."',
    audioUrl: '',
    visuals: [
      { iconUrl: '/visuals/wave.svg', description: 'Wave hello with a friendly smile.' },
      { iconUrl: '/visuals/speech.svg', description: 'Use simple greeting phrases.' },
    ],
    highlights: [
      { id: 'h1', phrase: 'Hello', emphasisType: 'background', color: '#ffe7a3', position: 0 },
      { id: 'h2', phrase: 'How are you?', emphasisType: 'underline' },
    ],
    visualAids: [
      {
        id: 'v1',
        imageUrl: '/visuals/wave.svg',
        altText: 'Waving hand icon',
        relatedPhrase: 'Hello',
        placement: 'inline',
      },
      {
        id: 'v2',
        imageUrl: '/visuals/speech.svg',
        altText: 'Speech bubble icon',
        relatedPhrase: 'How are you?',
        placement: 'below',
      },
    ],
    interactions: [
      {
        id: 'greet-1',
        type: 'true_false',
        question: 'Is "Hello" a friendly greeting?',
        questionImageUrl: '/images/greeting-hello.svg',
        questionAudioUrl: '/audio/greet-1-question.mp3',
        correctAnswer: 'True',
        hint: 'Think about what you say when meeting someone new.',
        explanation: '"Hello" is a common, friendly way to greet someone.',
        explanationAudioUrl: '/audio/greet-1-explanation.mp3',
        maxAttempts: 3,
        timeLimitSeconds: 25,
        feedback: {
          correct: 'Great job! "Hello" is a friendly greeting.',
          correctAudioUrl: '/audio/greet-1-correct.mp3',
          incorrect: 'Good effort. Let\'s try again.',
          incorrectAudioUrl: '/audio/greet-1-incorrect.mp3',
        },
        position: 0,
      },
      {
        id: 'greet-2',
        type: 'multiple_choice',
        question: 'Choose a friendly greeting.',
        questionImageUrl: '/images/greeting-options.svg',
        questionAudioUrl: '/audio/greet-2-question.mp3',
        options: ['Hello', 'Goodbye', 'Later'],
        correctAnswer: 'Hello',
        hint: 'It is a word you say at the start of a conversation.',
        explanation: '"Hello" is a friendly greeting.',
        explanationAudioUrl: '/audio/greet-2-explanation.mp3',
        maxAttempts: 3,
        timeLimitSeconds: 25,
        feedback: {
          correct: 'Yes! "Hello" is a friendly greeting.',
          correctAudioUrl: '/audio/greet-2-correct.mp3',
          incorrect: 'Nice try. Let\'s pick a greeting used at the start.',
          incorrectAudioUrl: '/audio/greet-2-incorrect.mp3',
        },
        position: 1,
      },
      {
        id: 'greet-3',
        type: 'click',
        question: 'Click the phrase you use to ask about someone.',
        questionImageUrl: '/images/asking-question.svg',
        questionAudioUrl: '/audio/greet-3-question.mp3',
        options: ['How are you?', 'Where is it?', 'See you later'],
        correctAnswer: 'How are you?',
        hint: 'It is a question about feelings.',
        explanation: '"How are you?" is used to ask about someone.',
        explanationAudioUrl: '/audio/greet-3-explanation.mp3',
        maxAttempts: 3,
        timeLimitSeconds: 30,
        feedback: {
          correct: 'Nice work! That question checks on someone.',
          correctAudioUrl: '/audio/greet-3-correct.mp3',
          incorrect: 'Good effort. Try the question about feelings.',
          incorrectAudioUrl: '/audio/greet-3-incorrect.mp3',
        },
        position: 2,
      },
      {
        id: 'greet-4',
        type: 'short_answer',
        question: 'Say or type a simple greeting.',
        questionImageUrl: '/images/type-greeting.svg',
        questionAudioUrl: '/audio/greet-4-question.mp3',
        correctAnswer: 'Hello',
        hint: 'Try "Hello".',
        explanation: '"Hello" is a simple, friendly greeting.',
        explanationAudioUrl: '/audio/greet-4-explanation.mp3',
        maxAttempts: 3,
        timeLimitSeconds: 35,
        feedback: {
          correct: 'Great greeting!',
          correctAudioUrl: '/audio/greet-4-correct.mp3',
          incorrect: 'Nice try. A simple greeting is "Hello".',
          incorrectAudioUrl: '/audio/greet-4-incorrect.mp3',
        },
        position: 3,
      },
      {
        id: 'greet-5',
        type: 'multiple_choice',
        question: 'Pick the best reply to "How are you?"',
        questionImageUrl: '/images/responding-greeting.svg',
        questionAudioUrl: '/audio/greet-5-question.mp3',
        options: ['I am good, thank you.', 'Blue.', 'At home.'],
        correctAnswer: 'I am good, thank you.',
        hint: 'It is a polite, full reply.',
        explanation: '"I am good, thank you." is a polite response.',
        explanationAudioUrl: '/audio/greet-5-explanation.mp3',
        maxAttempts: 3,
        timeLimitSeconds: 40,
        feedback: {
          correct: 'Excellent response!',
          correctAudioUrl: '/audio/greet-5-correct.mp3',
          incorrect: 'Good effort. Choose the polite full reply.',
          incorrectAudioUrl: '/audio/greet-5-incorrect.mp3',
        },
        position: 4,
      },
    ],
  },
  'lesson-vocabulary': {
    _id: 'lesson-vocabulary',
    title: 'Basic Words',
    textContent:
      'Let’s learn simple words for everyday items.\n\nSay the word and point to the item.\n\nRepeat each word slowly to build confidence.',
    audioUrl: '',
    visuals: [
      { iconUrl: '/visuals/speech.svg', description: 'Speak each word clearly.' },
      { iconUrl: '/visuals/sun.svg', description: 'Practice with objects around you.' },
    ],
    highlights: [
      { id: 'h3', phrase: 'simple words', emphasisType: 'bold' },
      { id: 'h4', phrase: 'Repeat', emphasisType: 'underline' },
    ],
    visualAids: [
      {
        id: 'v3',
        imageUrl: '/visuals/sun.svg',
        altText: 'Sun icon',
        relatedPhrase: 'Repeat',
        placement: 'side',
      },
    ],
    interactions: [
      {
        id: 'vocab-1',
        type: 'multiple_choice',
        question: 'Which word matches something you can sit on?',
        questionImageUrl: '/images/chair.svg',
        questionAudioUrl: '/audio/vocab-1-question.mp3',
        options: ['Chair', 'Apple', 'Rain'],
        correctAnswer: 'Chair',
        hint: 'Think of furniture you use every day.',
        explanation: 'A chair is furniture you sit on.',
        explanationAudioUrl: '/audio/vocab-1-explanation.mp3',
        maxAttempts: 3,
        timeLimitSeconds: 25,
        feedback: {
          correct: 'Yes! A chair is something you can sit on.',
          correctAudioUrl: '/audio/vocab-1-correct.mp3',
          incorrect: 'Good effort. Try the word for furniture you sit on.',
          incorrectAudioUrl: '/audio/vocab-1-incorrect.mp3',
        },
        position: 0,
      },
      {
        id: 'vocab-2',
        type: 'multiple_choice',
        question: 'Which word matches something you can eat?',
        questionImageUrl: '/images/apple.svg',
        questionAudioUrl: '/audio/vocab-2-question.mp3',
        options: ['Apple', 'Chair', 'Book'],
        correctAnswer: 'Apple',
        hint: 'It is a fruit.',
        explanation: 'An apple is a fruit you can eat.',
        explanationAudioUrl: '/audio/vocab-2-explanation.mp3',
        maxAttempts: 3,
        timeLimitSeconds: 25,
        feedback: {
          correct: 'Nice! An apple is something you can eat.',
          correctAudioUrl: '/audio/vocab-2-correct.mp3',
          incorrect: 'Nice try. Look for the fruit.',
          incorrectAudioUrl: '/audio/vocab-2-incorrect.mp3',
        },
        position: 1,
      },
      {
        id: 'vocab-3',
        type: 'click',
        question: 'Click the word for something you can read.',
        questionImageUrl: '/images/book.svg',
        questionAudioUrl: '/audio/vocab-3-question.mp3',
        options: ['Book', 'Cloud', 'Shoe'],
        correctAnswer: 'Book',
        hint: 'You open it to see words.',
        explanation: 'A book is something you read.',
        explanationAudioUrl: '/audio/vocab-3-explanation.mp3',
        maxAttempts: 3,
        timeLimitSeconds: 30,
        feedback: {
          correct: 'Great choice! A book is for reading.',
          correctAudioUrl: '/audio/vocab-3-correct.mp3',
          incorrect: 'Good effort. Try the item you can read.',
          incorrectAudioUrl: '/audio/vocab-3-incorrect.mp3',
        },
        position: 2,
      },
      {
        id: 'vocab-4',
        type: 'short_answer',
        question: 'Say or type a simple word for a place you live.',
        questionImageUrl: '/images/home.svg',
        questionAudioUrl: '/audio/vocab-4-question.mp3',
        correctAnswer: 'Home',
        hint: 'Think about where you sleep.',
        explanation: 'Home is the place you live.',
        explanationAudioUrl: '/audio/vocab-4-explanation.mp3',
        maxAttempts: 3,
        timeLimitSeconds: 35,
        feedback: {
          correct: 'Great word!',
          correctAudioUrl: '/audio/vocab-4-correct.mp3',
          incorrect: 'Nice try. A simple word is "Home".',
          incorrectAudioUrl: '/audio/vocab-4-incorrect.mp3',
        },
        position: 3,
      },
      {
        id: 'vocab-5',
        type: 'multiple_choice',
        question: 'Pick the word that means something you wear on your feet.',
        questionImageUrl: '/images/shoe.svg',
        questionAudioUrl: '/audio/vocab-5-question.mp3',
        options: ['Shoe', 'Leaf', 'Cloud'],
        correctAnswer: 'Shoe',
        hint: 'You wear it with socks.',
        explanation: 'A shoe is worn on your foot.',
        explanationAudioUrl: '/audio/vocab-5-explanation.mp3',
        maxAttempts: 3,
        timeLimitSeconds: 40,
        feedback: {
          correct: 'Excellent! A shoe goes on your foot.',
          correctAudioUrl: '/audio/vocab-5-correct.mp3',
          incorrect: 'Good effort. Choose the thing you wear.',
          incorrectAudioUrl: '/audio/vocab-5-incorrect.mp3',
        },
        position: 4,
      },
    ],
  },
  'lesson-numbers': {
    _id: 'lesson-numbers',
    title: 'Numbers',
    textContent:
      'Count from one to five.\n\nName a color for each number.\n\nMix numbers and colors to make learning fun.',
    audioUrl: '',
    visuals: [
      { iconUrl: '/visuals/sun.svg', description: 'Use bright colors to remember.' },
      { iconUrl: '/visuals/wave.svg', description: 'Count on your fingers as you learn.' },
    ],
    highlights: [
      { id: 'h5', phrase: 'Count from one to five', emphasisType: 'background' },
      { id: 'h6', phrase: 'colors', emphasisType: 'bold' },
    ],
    visualAids: [
      {
        id: 'v4',
        imageUrl: '/visuals/wave.svg',
        altText: 'Counting hand icon',
        relatedPhrase: 'Count',
        placement: 'inline',
      },
    ],
    interactions: [
      {
        id: 'numbers-1',
        type: 'click',
        question: 'Click the number that comes after 2.',
        questionImageUrl: '/images/number-sequence.svg',
        questionAudioUrl: '/audio/numbers-1-question.mp3',
        options: ['1', '3', '5'],
        correctAnswer: '3',
        hint: 'Count upward: 1, 2, 3.',
        explanation: 'The number after 2 is 3.',
        explanationAudioUrl: '/audio/numbers-1-explanation.mp3',
        maxAttempts: 3,
        timeLimitSeconds: 25,
        feedback: {
          correct: 'Great job! 3 comes after 2.',
          correctAudioUrl: '/audio/numbers-1-correct.mp3',
          incorrect: 'Good effort. Count up: 1, 2, 3.',
          incorrectAudioUrl: '/audio/numbers-1-incorrect.mp3',
        },
        position: 0,
      },
      {
        id: 'numbers-2',
        type: 'multiple_choice',
        question: 'Which number comes after 4?',
        questionImageUrl: '/images/counting-4-5.svg',
        questionAudioUrl: '/audio/numbers-2-question.mp3',
        options: ['3', '5', '6'],
        correctAnswer: '5',
        hint: 'Count forward: 4, 5.',
        explanation: 'The number after 4 is 5.',
        explanationAudioUrl: '/audio/numbers-2-explanation.mp3',
        maxAttempts: 3,
        timeLimitSeconds: 25,
        feedback: {
          correct: 'Nice! 5 comes after 4.',
          correctAudioUrl: '/audio/numbers-2-correct.mp3',
          incorrect: 'Nice try. Count forward to find 5.',
          incorrectAudioUrl: '/audio/numbers-2-incorrect.mp3',
        },
        position: 1,
      },
      {
        id: 'numbers-3',
        type: 'multiple_choice',
        question: 'Which set has three items?',
        questionImageUrl: '/images/counting-stars.svg',
        questionAudioUrl: '/audio/numbers-3-question.mp3',
        options: ['***', '**', '****'],
        correctAnswer: '***',
        hint: 'Count the stars.',
        explanation: 'Three stars means 3 items.',
        explanationAudioUrl: '/audio/numbers-3-explanation.mp3',
        maxAttempts: 3,
        timeLimitSeconds: 30,
        feedback: {
          correct: 'Great counting!',
          correctAudioUrl: '/audio/numbers-3-correct.mp3',
          incorrect: 'Good effort. Count the stars carefully.',
          incorrectAudioUrl: '/audio/numbers-3-incorrect.mp3',
        },
        position: 2,
      },
      {
        id: 'numbers-4',
        type: 'short_answer',
        question: 'Say or type the number after 1.',
        questionImageUrl: '/images/number-1-2.svg',
        questionAudioUrl: '/audio/numbers-4-question.mp3',
        correctAnswer: '2',
        hint: 'Count: 1, 2.',
        explanation: 'The number after 1 is 2.',
        explanationAudioUrl: '/audio/numbers-4-explanation.mp3',
        maxAttempts: 3,
        timeLimitSeconds: 35,
        feedback: {
          correct: 'Yes! The answer is 2.',
          correctAudioUrl: '/audio/numbers-4-correct.mp3',
          incorrect: 'Nice try. The answer is 2.',
          incorrectAudioUrl: '/audio/numbers-4-incorrect.mp3',
        },
        position: 3,
      },
      {
        id: 'numbers-5',
        type: 'multiple_choice',
        question: 'Choose the correct order from 1 to 3.',
        questionImageUrl: '/images/number-order.svg',
        questionAudioUrl: '/audio/numbers-5-question.mp3',
        options: ['1, 2, 3', '1, 3, 2', '2, 1, 3'],
        correctAnswer: '1, 2, 3',
        hint: 'Start at 1 and count up.',
        explanation: 'The correct order is 1, 2, 3.',
        explanationAudioUrl: '/audio/numbers-5-explanation.mp3',
        maxAttempts: 3,
        timeLimitSeconds: 40,
        feedback: {
          correct: 'Excellent ordering!',
          correctAudioUrl: '/audio/numbers-5-correct.mp3',
          incorrect: 'Good effort. Start at 1 and count up.',
          incorrectAudioUrl: '/audio/numbers-5-incorrect.mp3',
        },
        position: 4,
      },
    ],
  },
};

export default lessonSamples;
