const lessonSectionSamples = {
  'lesson-greetings': [
    {
      id: 'greet-s1',
      lessonId: 'lesson-greetings',
      title: 'Greeting basics',
      textContent: 'Hello! This section shows how to greet politely.',
      audioUrl: '/audio/greet-s1-narration.mp3',
      highlights: [
        { phrase: 'Hello', emphasisType: 'background', color: '#ffd700' },
        { phrase: 'greet', emphasisType: 'underline', color: '#667eea' },
        { phrase: 'politely', emphasisType: 'bold' },
      ],
      visuals: [
        { imageUrl: '/visuals/hello.svg', altText: 'Waving hand saying hello', relatedPhrase: 'Hello', placement: 'inline' },
        { imageUrl: '/visuals/how-are-you.svg', altText: 'People greeting each other politely', relatedPhrase: 'greet politely', placement: 'below' },
      ],
      interactions: [
        {
          id: 'greet-1',
          type: 'true_false',
          question: 'Is "Hello" a friendly greeting?',
          questionImageUrl: '/images/greeting-hello.svg',
          questionAudioUrl: '/audio/greet-1-question.mp3',
          correctAnswer: 'True',
          hint: 'Think about what you say when meeting someone new.',
          explanation: '"Hello" is a common, friendly way to greet someone.',
          explanationAudioUrl: '/audio/greet-1-explanation.mp3',
          maxAttempts: 3,
          timeLimitSeconds: 25,
          feedback: {
            correct: 'Great job! "Hello" is a friendly greeting.',
            correctAudioUrl: '/audio/greet-1-correct.mp3',
            incorrect: 'Good effort. Let\'s try again.',
            incorrectAudioUrl: '/audio/greet-1-incorrect.mp3',
          },
          position: 0,
        },
        {
          id: 'greet-2',
          type: 'multiple_choice',
          question: 'Choose a friendly greeting.',
          questionImageUrl: '/images/greeting-options.svg',
          questionAudioUrl: '/audio/greet-2-question.mp3',
          options: ['Hello', 'Goodbye', 'Later'],
          correctAnswer: 'Hello',
          hint: 'It is a word you say at the start of a conversation.',
          explanation: '"Hello" is a friendly greeting.',
          explanationAudioUrl: '/audio/greet-2-explanation.mp3',
          maxAttempts: 3,
          timeLimitSeconds: 25,
          feedback: {
            correct: 'Yes! "Hello" is a friendly greeting.',
            correctAudioUrl: '/audio/greet-2-correct.mp3',
            incorrect: 'Nice try. Let\'s pick a greeting used at the start.',
            incorrectAudioUrl: '/audio/greet-2-incorrect.mp3',
          },
          position: 1,
        },
        {
          id: 'greet-3',
          type: 'click',
          question: 'Click the phrase you use to ask about someone.',
          questionImageUrl: '/images/asking-question.svg',
          questionAudioUrl: '/audio/greet-3-question.mp3',
          options: ['How are you?', 'Where is it?', 'See you later'],
          correctAnswer: 'How are you?',
          hint: 'It is a question about feelings.',
          explanation: '"How are you?" is used to ask about someone.',
          explanationAudioUrl: '/audio/greet-3-explanation.mp3',
          maxAttempts: 3,
          timeLimitSeconds: 30,
          feedback: {
            correct: 'Nice work! That question checks on someone.',
            correctAudioUrl: '/audio/greet-3-correct.mp3',
            incorrect: 'Good effort. Try the question about feelings.',
            incorrectAudioUrl: '/audio/greet-3-incorrect.mp3',
          },
          position: 2,
        },
        {
          id: 'greet-4',
          type: 'short_answer',
          question: 'Say or type a simple greeting.',
          questionImageUrl: '/images/type-greeting.svg',
          questionAudioUrl: '/audio/greet-4-question.mp3',
          correctAnswer: 'Hello',
          hint: 'Try "Hello".',
          explanation: '"Hello" is a simple, friendly greeting.',
          explanationAudioUrl: '/audio/greet-4-explanation.mp3',
          maxAttempts: 3,
          timeLimitSeconds: 35,
          feedback: {
            correct: 'Great greeting!',
            correctAudioUrl: '/audio/greet-4-correct.mp3',
            incorrect: 'Nice try. A simple greeting is "Hello".',
            incorrectAudioUrl: '/audio/greet-4-incorrect.mp3',
          },
          position: 3,
        },
        {
          id: 'greet-5',
          type: 'multiple_choice',
          question: 'Pick the best reply to "How are you?"',
          questionImageUrl: '/images/responding-greeting.svg',
          questionAudioUrl: '/audio/greet-5-question.mp3',
          options: ['I am good, thank you.', 'Blue.', 'At home.'],
          correctAnswer: 'I am good, thank you.',
          hint: 'It is a polite, full reply.',
          explanation: '"I am good, thank you." is a polite response.',
          explanationAudioUrl: '/audio/greet-5-explanation.mp3',
          maxAttempts: 3,
          timeLimitSeconds: 40,
          feedback: {
            correct: 'Excellent response!',
            correctAudioUrl: '/audio/greet-5-correct.mp3',
            incorrect: 'Good effort. Choose the polite full reply.',
            incorrectAudioUrl: '/audio/greet-5-incorrect.mp3',
          },
          position: 4,
        },
      ],
      order: 0,
    },
    {
      id: 'greet-s2',
      lessonId: 'lesson-greetings',
      title: 'Friendly phrases',
      textContent: 'Say "Hello" or "Hi" with a smile. Ask "How are you?"',
      audioUrl: '/audio/greet-s2-narration.mp3',
      highlights: [
        { phrase: 'Hello', emphasisType: 'background', color: '#ffd700' },
        { phrase: 'Hi', emphasisType: 'background', color: '#90caf9' },
        { phrase: 'smile', emphasisType: 'underline', color: '#f06292' },
        { phrase: 'How are you?', emphasisType: 'background', color: '#a5d6a7' },
      ],
      visuals: [
        { imageUrl: '/visuals/hello.svg', altText: 'Friendly wave', relatedPhrase: 'Hello', placement: 'inline' },
        { imageUrl: '/visuals/how-are-you.svg', altText: 'Friendly question: How are you?', relatedPhrase: 'How are you?', placement: 'below' },
      ],
      interactions: [
        {
          id: 'greet-s2-1',
          type: 'multiple_choice',
          question: 'What is a friendly way to say hello?',
          options: ['Hi!', 'Go away!', 'Not now.'],
          correctAnswer: 'Hi!',
          hint: 'Choose the warm and welcoming word.',
          explanation: '"Hi!" is a friendly and casual greeting.',
          maxAttempts: 3,
          timeLimitSeconds: 25,
          feedback: {
            correct: 'Perfect! "Hi!" is very friendly.',
            incorrect: 'Try again. Pick the warmest greeting.',
          },
          position: 0,
        },
        {
          id: 'greet-s2-2',
          type: 'true_false',
          question: 'Should you smile when greeting someone?',
          correctAnswer: 'True',
          hint: 'A smile makes people feel welcome.',
          explanation: 'Smiling when greeting makes you appear friendly and approachable.',
          maxAttempts: 3,
          timeLimitSeconds: 25,
          feedback: {
            correct: 'Exactly! A smile makes greetings warmer.',
            incorrect: 'Think about what makes people feel welcome.',
          },
          position: 1,
        },
        {
          id: 'greet-s2-3',
          type: 'short_answer',
          question: 'Type a friendly question you can ask someone.',
          correctAnswer: 'How are you',
          hint: 'Ask about their well-being.',
          explanation: '"How are you?" shows you care about the person.',
          maxAttempts: 3,
          timeLimitSeconds: 35,
          feedback: {
            correct: 'Great question! That\'s very friendly.',
            incorrect: 'Try asking "How are you?"',
          },
          position: 2,
        },
      ],
      order: 1,
    },
  ],
  'lesson-vocabulary': [
    {
      id: 'vocab-s1',
      lessonId: 'lesson-vocabulary',
      title: 'Everyday objects',
      textContent: 'Let\u2019s learn simple words for everyday items.',
      audioUrl: '/audio/vocab-s1-narration.mp3',
      highlights: [
        { phrase: 'simple words', emphasisType: 'background', color: '#b39ddb' },
        { phrase: 'everyday items', emphasisType: 'underline', color: '#667eea' },
      ],
      visuals: [
        { imageUrl: '/visuals/basic-words.svg', altText: 'Everyday objects and words', relatedPhrase: 'everyday items', placement: 'inline' },
      ],
      interactions: [
        {
          id: 'vocab-1',
          type: 'multiple_choice',
          question: 'Which word matches something you can sit on?',
          questionImageUrl: '/images/chair.svg',
          questionAudioUrl: '/audio/vocab-1-question.mp3',
          options: ['Chair', 'Apple', 'Rain'],
          correctAnswer: 'Chair',
          hint: 'Think of furniture you use every day.',
          explanation: 'A chair is furniture you sit on.',
          explanationAudioUrl: '/audio/vocab-1-explanation.mp3',
          maxAttempts: 3,
          timeLimitSeconds: 25,
          feedback: {
            correct: 'Yes! A chair is something you can sit on.',
            correctAudioUrl: '/audio/vocab-1-correct.mp3',
            incorrect: 'Good effort. Try the word for furniture you sit on.',
            incorrectAudioUrl: '/audio/vocab-1-incorrect.mp3',
          },
          position: 0,
        },
        {
          id: 'vocab-2',
          type: 'multiple_choice',
          question: 'Which word matches something you can eat?',
          questionImageUrl: '/images/apple.svg',
          questionAudioUrl: '/audio/vocab-2-question.mp3',
          options: ['Apple', 'Chair', 'Book'],
          correctAnswer: 'Apple',
          hint: 'It is a fruit.',
          explanation: 'An apple is a fruit you can eat.',
          explanationAudioUrl: '/audio/vocab-2-explanation.mp3',
          maxAttempts: 3,
          timeLimitSeconds: 25,
          feedback: {
            correct: 'Nice! An apple is something you can eat.',
            correctAudioUrl: '/audio/vocab-2-correct.mp3',
            incorrect: 'Nice try. Look for the fruit.',
            incorrectAudioUrl: '/audio/vocab-2-incorrect.mp3',
          },
          position: 1,
        },
        {
          id: 'vocab-3',
          type: 'click',
          question: 'Click the word for something you can read.',
          questionImageUrl: '/images/book.svg',
          questionAudioUrl: '/audio/vocab-3-question.mp3',
          options: ['Book', 'Cloud', 'Shoe'],
          correctAnswer: 'Book',
          hint: 'You open it to see words.',
          explanation: 'A book is something you read.',
          explanationAudioUrl: '/audio/vocab-3-explanation.mp3',
          maxAttempts: 3,
          timeLimitSeconds: 30,
          feedback: {
            correct: 'Great choice! A book is for reading.',
            correctAudioUrl: '/audio/vocab-3-correct.mp3',
            incorrect: 'Good effort. Try the item you can read.',
            incorrectAudioUrl: '/audio/vocab-3-incorrect.mp3',
          },
          position: 2,
        },
        {
          id: 'vocab-4',
          type: 'short_answer',
          question: 'Say or type a simple word for a place you live.',
          questionImageUrl: '/images/home.svg',
          questionAudioUrl: '/audio/vocab-4-question.mp3',
          correctAnswer: 'Home',
          hint: 'Think about where you sleep.',
          explanation: 'Home is the place you live.',
          explanationAudioUrl: '/audio/vocab-4-explanation.mp3',
          maxAttempts: 3,
          timeLimitSeconds: 35,
          feedback: {
            correct: 'Great word!',
            correctAudioUrl: '/audio/vocab-4-correct.mp3',
            incorrect: 'Nice try. A simple word is "Home".',
            incorrectAudioUrl: '/audio/vocab-4-incorrect.mp3',
          },
          position: 3,
        },
        {
          id: 'vocab-5',
          type: 'multiple_choice',
          question: 'Pick the word that means something you wear on your feet.',
          questionImageUrl: '/images/shoe.svg',
          questionAudioUrl: '/audio/vocab-5-question.mp3',
          options: ['Shoe', 'Leaf', 'Cloud'],
          correctAnswer: 'Shoe',
          hint: 'You wear it with socks.',
          explanation: 'A shoe is worn on your foot.',
          explanationAudioUrl: '/audio/vocab-5-explanation.mp3',
          maxAttempts: 3,
          timeLimitSeconds: 40,
          feedback: {
            correct: 'Excellent! A shoe goes on your foot.',
            correctAudioUrl: '/audio/vocab-5-correct.mp3',
            incorrect: 'Good effort. Choose the thing you wear.',
            incorrectAudioUrl: '/audio/vocab-5-incorrect.mp3',
          },
          position: 4,
        },
      ],
      order: 0,
    },
    {
      id: 'vocab-s2',
      lessonId: 'lesson-vocabulary',
      title: 'People and places',
      textContent: 'Practice words for people and places you see daily.',
      audioUrl: '/audio/vocab-s2-narration.mp3',
      highlights: [
        { phrase: 'people', emphasisType: 'background', color: '#ffd700' },
        { phrase: 'places', emphasisType: 'background', color: '#90caf9' },
        { phrase: 'daily', emphasisType: 'underline', color: '#f06292' },
      ],
      visuals: [
        { imageUrl: '/visuals/sun.svg', altText: 'Sun icon representing daily life', relatedPhrase: 'daily', placement: 'inline' },
      ],
      interactions: [
        {
          id: 'vocab-s2-1',
          type: 'multiple_choice',
          question: 'Where do you go to buy food?',
          options: ['Store', 'Sky', 'Tree'],
          correctAnswer: 'Store',
          hint: 'You go shopping there.',
          explanation: 'A store is a place where you buy things like food.',
          maxAttempts: 3,
          timeLimitSeconds: 25,
          feedback: {
            correct: 'Yes! You buy food at a store.',
            incorrect: 'Think about where people shop.',
          },
          position: 0,
        },
        {
          id: 'vocab-s2-2',
          type: 'click',
          question: 'Click the word for a person who teaches.',
          options: ['Teacher', 'Leaf', 'Door'],
          correctAnswer: 'Teacher',
          hint: 'This person helps you learn.',
          explanation: 'A teacher is someone who helps you learn new things.',
          maxAttempts: 3,
          timeLimitSeconds: 30,
          feedback: {
            correct: 'Excellent! A teacher helps you learn.',
            incorrect: 'Try the word for someone who teaches.',
          },
          position: 1,
        },
        {
          id: 'vocab-s2-3',
          type: 'short_answer',
          question: 'Type a word for a person in your family.',
          correctAnswer: 'Mother',
          hint: 'Think of mom, dad, or sister.',
          explanation: 'Family members include mother, father, sister, and brother.',
          maxAttempts: 3,
          timeLimitSeconds: 35,
          feedback: {
            correct: 'Great! That\'s a family member.',
            incorrect: 'Try words like mother, father, or sister.',
          },
          position: 2,
        },
      ],
      order: 1,
    },
    {
      id: 'vocab-s3',
      lessonId: 'lesson-vocabulary',
      title: 'Action words',
      textContent: 'Say simple action words like "eat", "walk", and "read".',
      audioUrl: '/audio/vocab-s3-narration.mp3',
      highlights: [
        { phrase: 'action words', emphasisType: 'background', color: '#a5d6a7' },
        { phrase: 'eat', emphasisType: 'background', color: '#ffab91' },
        { phrase: 'walk', emphasisType: 'background', color: '#90caf9' },
        { phrase: 'read', emphasisType: 'background', color: '#ce93d8' },
      ],
      visuals: [
        { imageUrl: '/visuals/speech.svg', altText: 'Speech bubble for saying action words', relatedPhrase: 'Say', placement: 'below' },
      ],
      interactions: [
        {
          id: 'vocab-s3-1',
          type: 'multiple_choice',
          question: 'What action do you do with food?',
          options: ['Eat', 'Fly', 'Sleep'],
          correctAnswer: 'Eat',
          hint: 'You do this when you are hungry.',
          explanation: 'Eat is the action of consuming food.',
          maxAttempts: 3,
          timeLimitSeconds: 25,
          feedback: {
            correct: 'Perfect! You eat food.',
            incorrect: 'Think about what you do with food.',
          },
          position: 0,
        },
        {
          id: 'vocab-s3-2',
          type: 'click',
          question: 'Click the action you do with your legs.',
          options: ['Walk', 'Think', 'Sing'],
          correctAnswer: 'Walk',
          hint: 'You move from one place to another.',
          explanation: 'Walk means to move by using your legs.',
          maxAttempts: 3,
          timeLimitSeconds: 30,
          feedback: {
            correct: 'Yes! You walk with your legs.',
            incorrect: 'Try the action that uses your legs.',
          },
          position: 1,
        },
        {
          id: 'vocab-s3-3',
          type: 'short_answer',
          question: 'Type an action you do with a book.',
          correctAnswer: 'Read',
          hint: 'You look at the words.',
          explanation: 'Read is the action of looking at and understanding written words.',
          maxAttempts: 3,
          timeLimitSeconds: 35,
          feedback: {
            correct: 'Great! You read a book.',
            incorrect: 'Try the word "read".',
          },
          position: 2,
        },
      ],
      order: 2,
    },
  ],
  'lesson-numbers': [
    {
      id: 'num-s1',
      lessonId: 'lesson-numbers',
      title: 'Counting up',
      textContent: 'Count from one to five. Name a color for each number.',
      audioUrl: '/audio/num-s1-narration.mp3',
      highlights: [
        { phrase: 'Count', emphasisType: 'background', color: '#ffd700' },
        { phrase: 'one to five', emphasisType: 'underline', color: '#667eea' },
        { phrase: 'color', emphasisType: 'bold' },
      ],
      visuals: [
        { imageUrl: '/visuals/numbers.svg', altText: 'Numbers one two three', relatedPhrase: 'Count', placement: 'inline' },
      ],
      interactions: [
        {
          id: 'numbers-1',
          type: 'click',
          question: 'Click the number that comes after 2.',
          questionImageUrl: '/images/number-sequence.svg',
          questionAudioUrl: '/audio/numbers-1-question.mp3',
          options: ['1', '3', '5'],
          correctAnswer: '3',
          hint: 'Count upward: 1, 2, 3.',
          explanation: 'The number after 2 is 3.',
          explanationAudioUrl: '/audio/numbers-1-explanation.mp3',
          maxAttempts: 3,
          timeLimitSeconds: 25,
          feedback: {
            correct: 'Great job! 3 comes after 2.',
            correctAudioUrl: '/audio/numbers-1-correct.mp3',
            incorrect: 'Good effort. Count up: 1, 2, 3.',
            incorrectAudioUrl: '/audio/numbers-1-incorrect.mp3',
          },
          position: 0,
        },
        {
          id: 'numbers-2',
          type: 'multiple_choice',
          question: 'Which number comes after 4?',
          questionImageUrl: '/images/counting-4-5.svg',
          questionAudioUrl: '/audio/numbers-2-question.mp3',
          options: ['3', '5', '6'],
          correctAnswer: '5',
          hint: 'Count forward: 4, 5.',
          explanation: 'The number after 4 is 5.',
          explanationAudioUrl: '/audio/numbers-2-explanation.mp3',
          maxAttempts: 3,
          timeLimitSeconds: 25,
          feedback: {
            correct: 'Nice! 5 comes after 4.',
            correctAudioUrl: '/audio/numbers-2-correct.mp3',
            incorrect: 'Nice try. Count forward to find 5.',
            incorrectAudioUrl: '/audio/numbers-2-incorrect.mp3',
          },
          position: 1,
        },
        {
          id: 'numbers-3',
          type: 'multiple_choice',
          question: 'Which set has three items?',
          questionImageUrl: '/images/counting-stars.svg',
          questionAudioUrl: '/audio/numbers-3-question.mp3',
          options: ['***', '**', '****'],
          correctAnswer: '***',
          hint: 'Count the stars.',
          explanation: 'Three stars means 3 items.',
          explanationAudioUrl: '/audio/numbers-3-explanation.mp3',
          maxAttempts: 3,
          timeLimitSeconds: 30,
          feedback: {
            correct: 'Great counting!',
            correctAudioUrl: '/audio/numbers-3-correct.mp3',
            incorrect: 'Good effort. Count the stars carefully.',
            incorrectAudioUrl: '/audio/numbers-3-incorrect.mp3',
          },
          position: 2,
        },
        {
          id: 'numbers-4',
          type: 'short_answer',
          question: 'Say or type the number after 1.',
          questionImageUrl: '/images/number-1-2.svg',
          questionAudioUrl: '/audio/numbers-4-question.mp3',
          correctAnswer: '2',
          hint: 'Count: 1, 2.',
          explanation: 'The number after 1 is 2.',
          explanationAudioUrl: '/audio/numbers-4-explanation.mp3',
          maxAttempts: 3,
          timeLimitSeconds: 35,
          feedback: {
            correct: 'Yes! The answer is 2.',
            correctAudioUrl: '/audio/numbers-4-correct.mp3',
            incorrect: 'Nice try. The answer is 2.',
            incorrectAudioUrl: '/audio/numbers-4-incorrect.mp3',
          },
          position: 3,
        },
        {
          id: 'numbers-5',
          type: 'multiple_choice',
          question: 'Choose the correct order from 1 to 3.',
          questionImageUrl: '/images/number-order.svg',
          questionAudioUrl: '/audio/numbers-5-question.mp3',
          options: ['1, 2, 3', '1, 3, 2', '2, 1, 3'],
          correctAnswer: '1, 2, 3',
          hint: 'Start at 1 and count up.',
          explanation: 'The correct order is 1, 2, 3.',
          explanationAudioUrl: '/audio/numbers-5-explanation.mp3',
          maxAttempts: 3,
          timeLimitSeconds: 40,
          feedback: {
            correct: 'Excellent ordering!',
            correctAudioUrl: '/audio/numbers-5-correct.mp3',
            incorrect: 'Good effort. Start at 1 and count up.',
            incorrectAudioUrl: '/audio/numbers-5-incorrect.mp3',
          },
          position: 4,
        },
      ],
      order: 0,
    },
    {
      id: 'num-s2',
      lessonId: 'lesson-numbers',
      title: 'Number pairs',
      textContent: 'Match numbers with the correct number of objects.',
      audioUrl: '/audio/num-s2-narration.mp3',
      highlights: [
        { phrase: 'Match', emphasisType: 'background', color: '#ffd700' },
        { phrase: 'numbers', emphasisType: 'underline', color: '#667eea' },
        { phrase: 'objects', emphasisType: 'bold' },
      ],
      visuals: [
        { imageUrl: '/visuals/numbers.svg', altText: 'Counting objects', relatedPhrase: 'numbers', placement: 'inline' },
      ],
      interactions: [
        {
          id: 'num-s2-1',
          type: 'multiple_choice',
          question: 'How many apples are there? 🍎🍎',
          options: ['1', '2', '3'],
          correctAnswer: '2',
          hint: 'Count the apples carefully.',
          explanation: 'There are 2 apples.',
          maxAttempts: 3,
          timeLimitSeconds: 25,
          feedback: {
            correct: 'Perfect! There are 2 apples.',
            incorrect: 'Count again carefully.',
          },
          position: 0,
        },
        {
          id: 'num-s2-2',
          type: 'click',
          question: 'Click the number that matches four stars: ⭐⭐⭐⭐',
          options: ['3', '4', '5'],
          correctAnswer: '4',
          hint: 'Count each star.',
          explanation: 'There are 4 stars, so the answer is 4.',
          maxAttempts: 3,
          timeLimitSeconds: 30,
          feedback: {
            correct: 'Excellent counting! 4 stars = 4.',
            incorrect: 'Count the stars one by one.',
          },
          position: 1,
        },
        {
          id: 'num-s2-3',
          type: 'short_answer',
          question: 'How many books are here? 📚📚📚',
          correctAnswer: '3',
          hint: 'Count each book.',
          explanation: 'There are 3 books.',
          maxAttempts: 3,
          timeLimitSeconds: 35,
          feedback: {
            correct: 'Great! You counted 3 books.',
            incorrect: 'Try counting again: 1, 2, 3.',
          },
          position: 2,
        },
      ],
      order: 1,
    },
    {
      id: 'num-s3',
      lessonId: 'lesson-numbers',
      title: 'Counting forward',
      textContent: 'Say the next number after 1, 2, and 3.',
      audioUrl: '/audio/num-s3-narration.mp3',
      highlights: [
        { phrase: 'next number', emphasisType: 'background', color: '#a5d6a7' },
        { phrase: '1', emphasisType: 'background', color: '#ffd700' },
        { phrase: '2', emphasisType: 'background', color: '#90caf9' },
        { phrase: '3', emphasisType: 'background', color: '#ce93d8' },
      ],
      visuals: [
        { imageUrl: '/visuals/numbers.svg', altText: 'Number sequence 1 2 3', relatedPhrase: 'number', placement: 'inline' },
        { imageUrl: '/visuals/speech.svg', altText: 'Speech bubble for saying numbers', relatedPhrase: 'Say', placement: 'below' },
      ],
      interactions: [
        {
          id: 'num-s3-1',
          type: 'multiple_choice',
          question: 'What number comes after 3?',
          options: ['2', '4', '5'],
          correctAnswer: '4',
          hint: 'Count: 1, 2, 3, and then...',
          explanation: 'After 3 comes 4.',
          maxAttempts: 3,
          timeLimitSeconds: 25,
          feedback: {
            correct: 'Perfect! 4 comes after 3.',
            incorrect: 'Count forward: 3, 4.',
          },
          position: 0,
        },
        {
          id: 'num-s3-2',
          type: 'true_false',
          question: 'Does 5 come after 4?',
          correctAnswer: 'True',
          hint: 'Count: 4, 5.',
          explanation: 'Yes, 5 comes right after 4.',
          maxAttempts: 3,
          timeLimitSeconds: 25,
          feedback: {
            correct: 'Exactly! 5 follows 4.',
            incorrect: 'Count forward from 4.',
          },
          position: 1,
        },
        {
          id: 'num-s3-3',
          type: 'short_answer',
          question: 'Type the number after 2.',
          correctAnswer: '3',
          hint: 'Count: 1, 2, 3.',
          explanation: 'The number after 2 is 3.',
          maxAttempts: 3,
          timeLimitSeconds: 35,
          feedback: {
            correct: 'Excellent! 3 comes after 2.',
            incorrect: 'Try counting: 2, 3.',
          },
          position: 2,
        },
      ],
      order: 2,
    },
  ],
};

export default lessonSectionSamples;
